<a href="https://colab.research.google.com/github/baba8959/Numpy-Task---2-Baba-shaik/blob/main/Numpy_tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Task - 2 (Baba Shaik)



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [4]:
import numpy as np
np.__version__

'1.21.6'

In [6]:
np.show_config()

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE4

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [7]:
import numpy as np
null_vector = np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [8]:
import numpy as np
np.arange(1,100,10).size

10

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [9]:
import numpy as np
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [ ]:
import numpy as np
np.arange(1,100,10).size

10

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [12]:
from numpy.core.getlimits import array
import numpy as np
def function():
  array = np.zeros(10,dtype=int)
  array[4] = 10
  array[7] = 20
  return array
function()

array([ 0,  0,  0,  0, 10,  0,  0, 20,  0,  0])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [13]:
import numpy as np
array = np.arange(10,49)
array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [14]:
import numpy as np
array = np.arange(1,10)
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [21]:
import numpy as np
x = np.arange(2,11).reshape(3,3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [22]:
import numpy as np
numbers = [1,2,0,0,4,0]
print(f"Numbers = {numbers}")
zerosIndices = np.nonzero (numbers)
print(zerosIndices)

Numbers = [1, 2, 0, 0, 4, 0]
(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [23]:
import numpy as np
eye = np.eye(3)
eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [25]:
import numpy as np
a = np.random.random((3,3,3))
print(a)

[[[0.07266327 0.43179744 0.76276679]
  [0.63906497 0.16433602 0.41531742]
  [0.78154287 0.41703488 0.98245522]]

 [[0.70576478 0.30716553 0.21459715]
  [0.18597381 0.45283406 0.88909862]
  [0.55066713 0.74530253 0.39517432]]

 [[0.23470105 0.06765544 0.57826808]
  [0.45767843 0.50426199 0.68432769]
  [0.20874395 0.68514407 0.06437123]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [4]:
import numpy as np
array = np.random.randint (100, size=(10,10))
array

array([[52, 71,  1, 47, 10, 34, 58, 98, 15, 54],
       [88, 36, 48, 97, 28, 89, 92, 53, 56, 76],
       [60, 53, 71, 99,  5, 97, 65, 45, 80, 80],
       [10, 50, 67, 84, 92, 28, 15, 64, 12, 14],
       [67, 19, 14, 88, 15, 39, 91, 41, 38, 27],
       [56, 61, 45, 57, 61, 21, 16, 57, 89, 41],
       [72, 81, 66,  9, 53, 77, 56, 96, 94, 93],
       [70, 43, 16, 52,  9, 65, 47, 82, 63, 55],
       [31, 71, 35, 99, 10, 66, 26, 15, 17, 54],
       [29,  4, 43, 47, 62, 15, 30, 25, 92,  9]])

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [67]:
import numpy as np
arr = np.random.rand(30)
arr.mean()

0.44499587617709757

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [66]:
import numpy as np
arr = np.ones((5,5),dtype = 'int')
arr[1:-1,1:-1] = np.zeros((3,3),dtype = 'int')
arr

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [65]:
import numpy as np
arr = np.random.random((5,5))
arr = np.pad(arr,pad_width=(1,1),mode = 'constant',constant_values = 0)
arr

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.78025352, 0.14926268, 0.60936799, 0.54708011,
        0.63214574, 0.        ],
       [0.        , 0.7739816 , 0.04231225, 0.33672769, 0.11607516,
        0.28116439, 0.        ],
       [0.        , 0.63817122, 0.11562045, 0.46728992, 0.56544941,
        0.99631463, 0.        ],
       [0.        , 0.02518262, 0.92408077, 0.59943243, 0.25190651,
        0.70206869, 0.        ],
       [0.        , 0.2405902 , 0.09150385, 0.10872584, 0.51173195,
        0.44290944, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ]])

#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [64]:
np.nan in set([np.nan])

True

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [6]:
arr = np.diag((1,2,3,4))
arr = np.pad(arr,pad_width = ((1,0),(0,1)),mode = 'constant')
arr

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [3]:
import numpy as np
x = np.ones((3,3))
print("checkeboard pattern:")
x =np.zeros((8,8),dtype=int)
x[1::2,::2]=1
x[::2,1::2]=1
print(x)


checkeboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [7]:
import numpy as np
arr = np.arange(6*7*8).reshape(6,7,8)
arr[1,5,3]

99

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [4]:
import numpy as np
x = np.ones((3,3))
print("checkeboard pattern:")
x =np.zeros((8,8),dtype=int)
x[1::2,::2]=1
x[::2,1::2]=1
print(x)

checkeboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [9]:
import numpy as np
arr = np.random.random((5,5)).astype('d')
arr_max,arr_min = arr.max(),arr.min()

arr = (arr-arr_min)/(arr_max - arr_min)
print(arr)
print(arr.dtype)

[[0.33971351 0.81352322 0.97434269 0.         0.27566222]
 [0.71687909 0.1373061  0.43636682 0.66489872 0.86269264]
 [0.43800704 0.64782732 0.09329484 0.74059839 0.57294913]
 [0.90400718 0.9014805  0.56033653 0.1741733  1.        ]
 [0.51924436 0.29317724 0.41833482 0.23144094 0.24070022]]
float64


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [10]:
import numpy as np
RGBA = np.dtype([('red',np.uint8),('green',np.uint8),('blue',np.uint8),('alpha',np.uint8)])
color = np.array((1,2,4,3),dtype = RGBA)
print(color['red'])
type(color)

1


numpy.ndarray

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [11]:
import numpy as np
arr_1 = np.random.random((5,3))
arr_2 = np.random.random((3,2))
print(arr_1 @ arr_2)
np.dot(arr_1,arr_2)

[[1.13196142 0.99794807]
 [1.03405979 0.61838928]
 [0.92281494 0.84016973]
 [0.18119879 0.37036087]
 [0.74286453 1.10237577]]


array([[1.13196142, 0.99794807],
       [1.03405979, 0.61838928],
       [0.92281494, 0.84016973],
       [0.18119879, 0.37036087],
       [0.74286453, 1.10237577]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [12]:
import numpy as np
arr = np.arange(16)
print(arr>=3)
arr[(arr>=3) & (arr<=8)]*=(-1)
print(arr)

arr = np.arange(16)

[False False False  True  True  True  True  True  True  True  True  True
  True  True  True  True]
[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10 11 12 13 14 15]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [13]:
import numpy as np
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [14]:
import numpy as np
np.array([np.nan]).astype(int).astype(float)

array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [15]:
import numpy as np
arr = np.random.random((5,5))
print(arr)
arr = np.round(arr,2)
print(arr)

[[0.89099987 0.10116352 0.28262855 0.49298842 0.84205571]
 [0.84919734 0.76336428 0.08817448 0.57730752 0.54961657]
 [0.9045183  0.93471577 0.11594757 0.26825793 0.11969555]
 [0.75265527 0.15779996 0.76281639 0.72524291 0.21450159]
 [0.96070121 0.22739062 0.34081474 0.92407449 0.52245767]]
[[0.89 0.1  0.28 0.49 0.84]
 [0.85 0.76 0.09 0.58 0.55]
 [0.9  0.93 0.12 0.27 0.12]
 [0.75 0.16 0.76 0.73 0.21]
 [0.96 0.23 0.34 0.92 0.52]]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [21]:
import numpy as np
arr_1 = np.arange(9).reshape(3,3)
arr_2 = np.array([[0,1,2],[3,4,5],[1,1,1]])

indices = [i for i,x,y in enumerate(arr_1,arr_2) if (x ==y)]
indices = (arr_1 == arr_2)
arr_1[indices]
def find_common()

SyntaxError: ignored

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [23]:
import numpy as np
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

_ = np.seterr(**defaults)

with np.errstate(divide='ignore'):
     Z = np.ones(1) / 0

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [24]:
np.sqrt(-1) == np.emath.sqrt(-1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [27]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [29]:
import numpy as np
A = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(A)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [30]:
import numpy as np
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.dot(A,B)

-4.5

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [31]:
import numpy as np
Z = np.random.uniform(0,10,10)

print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))

[3. 3. 2. 4. 6. 3. 2. 2. 3. 2.]
[3. 3. 2. 4. 6. 3. 2. 2. 3. 2.]
[3. 3. 2. 4. 6. 3. 2. 2. 3. 2.]
[3 3 2 4 6 3 2 2 3 2]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [32]:
import numpy as np
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [33]:
import numpy as np
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [34]:
import numpy as np
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [35]:
import numpy as np
Z = np.random.random(10)
Z.sort()
print(Z)

[0.05219895 0.17014908 0.17429854 0.23119569 0.49266747 0.76662243
 0.81507747 0.90151919 0.9479114  0.98683495]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [37]:
import numpy as np
import functools as ft
Z = np.arange(10)
ft.reduce(np.add,Z,0)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [39]:
import numpy as np
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
print(A)
print('*'*60)
print(B)
print('*'*60)
equal = np.allclose(A,B)
print(equal)
equal = np.array_equal(A,B)
print(equal)

[1 0 0 0 1]
************************************************************
[1 0 0 1 0]
************************************************************
False
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [41]:
import numpy as np
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] 

0.0

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [42]:
import numpy as np
z= np.random.randint(0,9,(10,2))
x,y = z[:,0], z[:,1]
r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)
poles = np.c_[r,t]
print(poles)

[[ 4.47213595  0.46364761]
 [ 5.          0.64350111]
 [ 9.21954446  0.86217005]
 [ 5.          0.92729522]
 [ 8.06225775  0.51914611]
 [ 5.83095189  1.03037683]
 [ 4.47213595  0.46364761]
 [ 7.21110255  0.5880026 ]
 [11.3137085   0.78539816]
 [ 1.41421356  0.78539816]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [43]:
import numpy as np
arr = np.random.random(10)
print(arr)
arr[arr.argmax()] = 0
print(arr)

[3.72263018e-01 4.55240863e-04 8.35836492e-01 8.01362993e-01
 1.22577746e-01 4.38503161e-01 6.41289325e-01 1.74405585e-01
 7.00980888e-01 1.50255781e-01]
[3.72263018e-01 4.55240863e-04 0.00000000e+00 8.01362993e-01
 1.22577746e-01 4.38503161e-01 6.41289325e-01 1.74405585e-01
 7.00980888e-01 1.50255781e-01]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [45]:
import numpy as np
Y = np.random.randint(0,11,10)
X = np.random.randint(11,22,10)
print(Y.reshape(1,10))
Y = np.tile(Y,(10,1))
print(X)
X  = np.tile(X,(10,1)).T
print(X)

C = 1/(X - Y)
C 

[[1 7 4 1 6 7 4 8 8 2]]
[15 11 12 18 12 11 21 19 15 19]
[[15 15 15 15 15 15 15 15 15 15]
 [11 11 11 11 11 11 11 11 11 11]
 [12 12 12 12 12 12 12 12 12 12]
 [18 18 18 18 18 18 18 18 18 18]
 [12 12 12 12 12 12 12 12 12 12]
 [11 11 11 11 11 11 11 11 11 11]
 [21 21 21 21 21 21 21 21 21 21]
 [19 19 19 19 19 19 19 19 19 19]
 [15 15 15 15 15 15 15 15 15 15]
 [19 19 19 19 19 19 19 19 19 19]]


array([[0.07142857, 0.125     , 0.09090909, 0.07142857, 0.11111111,
        0.125     , 0.09090909, 0.14285714, 0.14285714, 0.07692308],
       [0.1       , 0.25      , 0.14285714, 0.1       , 0.2       ,
        0.25      , 0.14285714, 0.33333333, 0.33333333, 0.11111111],
       [0.09090909, 0.2       , 0.125     , 0.09090909, 0.16666667,
        0.2       , 0.125     , 0.25      , 0.25      , 0.1       ],
       [0.05882353, 0.09090909, 0.07142857, 0.05882353, 0.08333333,
        0.09090909, 0.07142857, 0.1       , 0.1       , 0.0625    ],
       [0.09090909, 0.2       , 0.125     , 0.09090909, 0.16666667,
        0.2       , 0.125     , 0.25      , 0.25      , 0.1       ],
       [0.1       , 0.25      , 0.14285714, 0.1       , 0.2       ,
        0.25      , 0.14285714, 0.33333333, 0.33333333, 0.11111111],
       [0.05      , 0.07142857, 0.05882353, 0.05      , 0.06666667,
        0.07142857, 0.05882353, 0.07692308, 0.07692308, 0.05263158],
       [0.05555556, 0.08333333, 0.0666666

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [46]:
import numpy as np
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [49]:
import numpy as np
Z = np.zeros((int(1e4),int(1e4)))
Z = []
print(Z)

[]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [50]:
import numpy as np
arr = np.random.uniform(0,10,10)
scal = 5
arr_1 = np.abs(arr - 5)
ind = arr_1.argmin()
print(arr)
print('*'*60)
print(arr[ind])

[5.55063868 1.30940576 6.84992023 4.57284387 1.26749475 3.77062116
 4.16866623 8.07330315 1.90059845 7.97519147]
************************************************************
4.572843872669684


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [51]:
import numpy as np
Z = np.zeros(10, [ ('position', [ ('x', float),
                                  ('y', float)]),
                   ('color',    [ ('r', float),
                                  ('g', float),
                                  ('b', float)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [53]:
import numpy as np
arr = np.random.random((100,2))
X,Y = np.atleast_2d(arr[:,0],arr[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
import scipy
import scipy.spatial
Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.59510118 0.24474796 0.33397743 0.39580812 0.34696827
  0.62667579 0.31138139 0.23023046 0.88930988]
 [0.59510118 0.         0.70281489 0.28241281 0.9312005  0.46027269
  0.36393935 0.30550519 0.44953745 0.74083765]
 [0.24474796 0.70281489 0.         0.42109706 0.23343972 0.5796083
  0.83016783 0.39871966 0.45598747 0.75639276]
 [0.33397743 0.28241281 0.42109706 0.         0.64879369 0.36281389
  0.47573948 0.02369174 0.27792696 0.6782363 ]
 [0.39580812 0.9312005  0.23343972 0.64879369 0.         0.74015814
  1.0210102  0.62573133 0.6260278  0.93110234]
 [0.34696827 0.46027269 0.5796083  0.36281389 0.74015814 0.
  0.30822486 0.35799639 0.12478817 1.04097063]
 [0.62667579 0.36393935 0.83016783 0.47573948 1.0210102  0.30822486
  0.         0.4868853  0.39915936 1.09022229]
 [0.31138139 0.30550519 0.39871966 0.02369174 0.62573133 0.35799639
  0.4868853  0.         0.26682186 0.68358866]
 [0.23023046 0.44953745 0.45598747 0.27792696 0.6260278  0.12478817
  0.39915936 0.266821

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [54]:
import numpy as np
Z = np.arange(10, dtype=np.float32)
Z_1 = Z.astype(np.float32, copy=False)
Z_1[0] = 2
print(Z)

[2. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [55]:
from io import StringIO

# Fake file 
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  import sys


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [56]:
import numpy as np
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [57]:
import numpy as np
sigma,myu = 1.0,0.0

X,Y  = np.meshgrid(np.linspace(-1,1,10),np.linspace(-1,1,10))
D = np.sqrt(X**2+Y**2)
G = np.exp(-(D-myu)**2/(2*sigma**2))
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [58]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

np.put(Z,11,1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [59]:
import numpy as np
X = np.random.rand(5, 10)
Y = X - X.mean(axis = 1,keepdims = True)
print(Y)
X.mean(axis = 1).reshape(-1,1) == X.mean(axis = 1,keepdims =True)

[[ 0.18365141 -0.34284877 -0.45845231  0.40571207 -0.39722821 -0.27451702
   0.4682003   0.03700052  0.06800602  0.31047598]
 [ 0.04935554 -0.16605711 -0.29333101  0.11691346  0.10267048  0.42687709
   0.37192734 -0.3506594   0.10147507 -0.35917145]
 [-0.19615475  0.42516527  0.26527988 -0.25702164 -0.14264518 -0.38484612
   0.36914386  0.14009125  0.26416831 -0.48318088]
 [-0.13483909  0.21914252  0.21877649  0.13438984  0.02525923  0.13502212
   0.20252016 -0.62137109  0.17801976 -0.35691993]
 [ 0.0963184   0.29410238 -0.36387843 -0.01319753  0.44687566 -0.2678076
  -0.28139633 -0.2382026   0.59663562 -0.26944956]]


array([[ True],
       [ True],
       [ True],
       [ True],
       [ True]])

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [61]:
Z = np.random.randint(0,10,(5,5))
print(Z)
Z_1 = Z
for ind in range(5):
     Z_1[:,ind].sort()
print(Z_1)
print(Z[(-Z)[:,1].argsort()])
print(Z[:,Z[1,:].argsort()])

[[3 7 7 1 0]
 [0 8 0 2 0]
 [4 0 9 4 8]
 [7 2 3 3 1]
 [7 0 5 9 0]]
[[0 0 0 1 0]
 [3 0 3 2 0]
 [4 2 5 3 0]
 [7 7 7 4 1]
 [7 8 9 9 8]]
[[7 8 9 9 8]
 [7 7 7 4 1]
 [4 2 5 3 0]
 [0 0 0 1 0]
 [3 0 3 2 0]]
[[0 0 1 0 0]
 [0 0 2 3 3]
 [2 0 3 4 5]
 [7 1 4 7 7]
 [8 8 9 7 9]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [62]:
import numpy as np
Z = np.random.randint(0,3,(3,10))
Z[:,1] = 0
Z = Z.astype(bool)
print(Z)
print(~Z)
(Z).any(axis = 0)

[[False False False  True False  True  True False False  True]
 [False False False False False False  True False  True  True]
 [False False False  True  True  True  True  True  True  True]]
[[ True  True  True False  True False False  True  True False]
 [ True  True  True  True  True  True False  True False False]
 [ True  True  True False False False False False False False]]


array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [68]:
import numpy as np
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.5600108430342721


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [69]:
import numpy as np
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [70]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [71]:
import numpy as np
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

# Another solution
# Author: Bartosz Telenczuk
np.add.at(Z, I, 1)
print(Z)

[2. 4. 3. 6. 1. 2. 5. 3. 1. 3.]
[ 3.  7.  5. 11.  1.  3.  9.  5.  1.  5.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [72]:
import numpy as np
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [73]:
import numpy as np
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

w, h = 256, 256
I = np.random.randint(0,4,(h,w,3), dtype=np.uint8)

I24 = np.dot(I.astype(np.uint32),[1,256,65536])

n = len(np.unique(I24))
print(n)

64
64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [74]:
import numpy as np
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[44 74 49 52]
 [60 47 49 43]
 [46 43 45 47]]
[[44 74 49 52]
 [60 47 49 43]
 [46 43 45 47]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [75]:
import numpy as np
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.37024579 0.53057402 0.66290294 0.59954069 0.46659747 0.55192822
 0.41188668 0.42872483 0.23358078 0.41719592]
0    0.370246
1    0.530574
2    0.662903
3    0.599541
4    0.466597
5    0.551928
6    0.411887
7    0.428725
8    0.233581
9    0.417196
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [76]:
import numpy as np
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)

array([0.12271414, 2.09020877, 0.99992798, 1.088817  , 1.26427528])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [77]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [78]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [80]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [81]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 3,  8) ( 3, 44) ( 3, 52) ( 3, 60) ( 7, 43) ( 7, 59) ( 8, 52) (13, 75)
 (13, 82) (15, 63) (15, 94) (16, 75) (16, 83) (17, 57) (17, 74) (23, 85)
 (23, 99) (32, 56) (32, 91) (43, 59) (44, 60) (56, 91) (57, 74) (58, 81)
 (58, 93) (63, 94) (75, 82) (75, 83) (81, 93) (85, 99)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [82]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [83]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

from numpy.lib.stride_tricks import sliding_window_view

Z = np.arange(20)
print(sliding_window_view(Z, window_shape=3).mean(axis=-1))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [84]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

Z = np.arange(10)
print(sliding_window_view(Z, window_shape=3))

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [85]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([ 0.79768142, -0.37587501,  0.31108173, -0.04210889, -0.00555068,
       -0.89741785, -0.65137905,  0.1769629 ,  0.83777321, -0.15707199,
        0.92096759,  0.67471548,  0.87250829,  0.51256852,  0.51745055,
        0.09810869,  0.30076253, -0.30288137, -0.88062664, -0.95297673,
        0.3594944 ,  0.77610846,  0.27093285, -0.00959586, -0.38079337,
        0.29414765,  0.53616617,  0.32255333, -0.70751039,  0.71183513,
        0.64351421,  0.85611757, -0.41153911,  0.26341814,  0.03916354,
        0.8239333 , -0.57053622,  0.79517676, -0.67100802, -0.08938561,
        0.79196176,  0.245342  ,  0.99411385, -0.43837712,  0.30184376,
       -0.75904603, -0.48743302, -0.20677009, -0.75249807, -0.98176526,
        0.1332059 , -0.61330336,  0.56568051,  0.32585267, -0.33285367,
        0.90361766,  0.49792975, -0.63990822,  0.01610553, -0.14745755,
        0.82607828,  0.07801007,  0.98690915,  0.55468124, -0.75772539,
       -0.44961749, -0.91173197, -0.92052519, -0.96277399,  0.04

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [86]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[14.73576681  1.92788967  9.74660562 11.00396486  5.93972623  1.80143166
 19.51469665  3.5952093  11.18145921 17.00245154]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [87]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 4.59469634  2.73037211  8.76891968  6.20618577  1.09388895  7.08577439
   0.95108025  1.58708657  7.04768854  0.69441387]
 [ 8.18899128  0.18070938  4.03390791  0.06284283 12.17101294 10.44527758
   0.69439502  9.78911186 19.49522825 13.23452661]
 [ 2.62815009  4.69071454  0.64313234  3.42430393 13.03974166  4.89970693
   4.68628673 10.41531234 15.68678152  9.51946942]
 [ 4.88799905  2.03362317  0.5198234   0.81912369 11.04006337  7.18517214
   2.24040728  8.49405948 15.82166943  9.59476765]
 [ 9.49959338  7.14151343  6.56696385  9.90626456  0.53760124 11.9939232
   3.93113004  3.01523648  9.6645303   3.2175126 ]
 [ 6.95613006  1.94885172  2.41749695  3.80022481  6.11206965  9.33661563
   0.48571125  3.59995673 13.28707069  6.9649262 ]
 [ 6.2869951  13.65942036  1.62706946 11.52027044 17.9049286   4.0580629
  13.85929688 14.93413793 12.56042184  6.58846113]
 [ 7.32073164  1.31464953  0.50154424  2.68858397  7.91273574  9.66431659
   0.54603832  5.43923898 15.13061268  8.82675493]
 [

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [88]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[8 9 3 4 4 9 6 6 3 4]
 [1 2 6 0 7 9 5 3 9 0]
 [5 4 7 8 8 1 2 1 0 3]
 [4 2 8 4 5 2 4 5 6 4]
 [7 3 0 7 2 4 4 8 5 6]
 [4 4 2 5 1 8 8 1 1 8]
 [8 2 4 7 3 7 0 1 1 3]
 [4 8 4 0 1 9 4 5 6 7]
 [3 8 8 4 4 4 3 0 1 3]
 [2 9 4 7 8 5 1 0 3 7]]
[[0 0 0 0 0]
 [0 8 9 3 4]
 [0 1 2 6 0]
 [0 5 4 7 8]
 [0 4 2 8 4]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [89]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

Z = np.arange(1, 15, dtype=np.uint32)
print(sliding_window_view(Z, window_shape=4))

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [91]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)
rank = np.linalg.matrix_rank(Z)
print(rank)

10
10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [92]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

6


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [93]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

Z = np.random.randint(0,5,(10,10))
print(sliding_window_view(Z, window_shape=(3, 3)))

[[[[1 1 3]
   [2 0 0]
   [3 3 3]]

  [[1 3 0]
   [0 0 4]
   [3 3 1]]

  [[3 0 4]
   [0 4 3]
   [3 1 0]]

  [[0 4 0]
   [4 3 3]
   [1 0 1]]

  [[4 0 2]
   [3 3 1]
   [0 1 4]]

  [[0 2 2]
   [3 1 3]
   [1 4 3]]

  [[2 2 4]
   [1 3 3]
   [4 3 4]]

  [[2 4 2]
   [3 3 1]
   [3 4 2]]]


 [[[2 0 0]
   [3 3 3]
   [0 0 4]]

  [[0 0 4]
   [3 3 1]
   [0 4 3]]

  [[0 4 3]
   [3 1 0]
   [4 3 3]]

  [[4 3 3]
   [1 0 1]
   [3 3 3]]

  [[3 3 1]
   [0 1 4]
   [3 3 0]]

  [[3 1 3]
   [1 4 3]
   [3 0 3]]

  [[1 3 3]
   [4 3 4]
   [0 3 2]]

  [[3 3 1]
   [3 4 2]
   [3 2 1]]]


 [[[3 3 3]
   [0 0 4]
   [2 2 4]]

  [[3 3 1]
   [0 4 3]
   [2 4 4]]

  [[3 1 0]
   [4 3 3]
   [4 4 1]]

  [[1 0 1]
   [3 3 3]
   [4 1 1]]

  [[0 1 4]
   [3 3 0]
   [1 1 0]]

  [[1 4 3]
   [3 0 3]
   [1 0 3]]

  [[4 3 4]
   [0 3 2]
   [0 3 2]]

  [[3 4 2]
   [3 2 1]
   [3 2 4]]]


 [[[0 0 4]
   [2 2 4]
   [1 2 2]]

  [[0 4 3]
   [2 4 4]
   [2 2 4]]

  [[4 3 3]
   [4 4 1]
   [2 4 3]]

  [[3 3 3]
   [4 1 1]
   [4 3 1]]

  [[3 3 0]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [94]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 7 10  8  4 12]
 [10  3  8 11  9]
 [ 8  8  6 42 15]
 [ 4 11 42  2  5]
 [12  9 15  5  9]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [95]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)


[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [96]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

Z = np.ones((16,16))
k = 4

windows = np.lib.stride_tricks.sliding_window_view(Z, (k, k))
S = windows[::k, ::k, ...].sum(axis=(-2, -1))

Z = np.ones((16, 16))
k = 4
print(sliding_window_view(Z, window_shape=(k, k))[::k, ::k].sum(axis=(-2, -1)))

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]
[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [97]:
def iterate(Z):
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [98]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9999 9997 9996 9998 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [99]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [100]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [101]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

3.78 s ± 8.86 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
184 ms ± 17.7 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
158 ms ± 973 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [102]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 1 2 3 4 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [103]:
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[4 4 1]
 [4 2 1]
 [0 0 4]
 [1 4 3]
 [3 0 0]
 [1 4 1]
 [3 4 0]
 [4 0 1]
 [1 3 4]
 [0 1 2]]
[[4 4 1]
 [4 2 1]
 [0 0 4]
 [1 4 3]
 [3 0 0]
 [1 4 1]
 [3 4 0]
 [4 0 1]
 [1 3 4]
 [0 1 2]]
[[4 4 1]
 [4 2 1]
 [0 0 4]
 [1 4 3]
 [3 0 0]
 [1 4 1]
 [3 4 0]
 [4 0 1]
 [1 3 4]
 [0 1 2]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [104]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

# Author: Daniel T. McDonald

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [105]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

# Author: Andreas Kouzelis
# NumPy >= 1.13
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 0]
 [0 0 1]
 [0 1 0]
 [1 1 0]
 [1 1 1]]
[[0 0 0]
 [0 0 1]
 [0 1 0]
 [1 1 0]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [106]:

A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       
np.einsum('i,i->i', A, B) 
np.einsum('i,i', A, B)    
np.einsum('i,j->ij', A, B)

array([[0.01076503, 0.00713403, 0.0377314 , 0.03929722, 0.00852624,
        0.00877797, 0.01471754, 0.01112677, 0.02846953, 0.04689295],
       [0.12037552, 0.0797734 , 0.42191595, 0.43942511, 0.09534117,
        0.09815607, 0.1645729 , 0.12442052, 0.3183489 , 0.52436125],
       [0.08064242, 0.0534421 , 0.28265151, 0.29438132, 0.06387131,
        0.06575708, 0.11025129, 0.08335226, 0.21326949, 0.35128205],
       [0.13403887, 0.08882817, 0.46980597, 0.48930253, 0.10616297,
        0.10929738, 0.18325292, 0.13854301, 0.35448344, 0.58387943],
       [0.0533779 , 0.03537378, 0.18708942, 0.19485348, 0.04227696,
        0.04352517, 0.07297626, 0.05517157, 0.14116488, 0.23251655],
       [0.08486607, 0.05624113, 0.2974554 , 0.30979956, 0.06721658,
        0.06920111, 0.11602571, 0.08771784, 0.2244395 , 0.36968048],
       [0.15505988, 0.10275889, 0.54348454, 0.56603871, 0.12281226,
        0.12643823, 0.21199205, 0.16027038, 0.41007625, 0.67544789],
       [0.04570242, 0.0302872 , 0.1601869

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [109]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                
r_int = np.linspace(0, r.max(), 200) 
x_int = np.interp(r_int, r, x)       
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [110]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [111]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.25723787  0.13667391]
